---
- hosts: bgp
  become: True
  roles:
    - bgp

- hosts: docker
  become: True
  roles:
    - docker

- hosts: vpn
  become: True
  roles:
    - vpnserver

- hosts: all
  become: True
  roles:
    - generic
    - monitoring