---
# Update APT cache
- name: apt update
  apt:
    update_cache: True

# Upgrade packages
- name: apt upgrade
  apt:
    upgrade: True

- name: Set timezone
  timezone:
    name: America/New_York

- name: Install basic packages
  apt:
    name: net-tools,unzip,wget,curl,zip,sudo,python3,python-is-python3,python-apt,nano
    state: present
    register: apt_status
    until: apt_status is success
    delay: 6
    retries: 10

- name: Add sudo user unixfy
  user:
    name: unixfy
    state: present
    update_password: on_create
    groups: sudo

- name: Add all SSH keys from vars/main.yml/sshkeys to authorized_keys of unixfy user
  authorized_key:
    exclusive: True
    state: present
    user: unixfy
    key: "{{ sshkeys|map(attribute='key')|join('\n') }}"

- name: Install SSH server
  apt:
    name: openssh-server
    state: present

- name: Ensure SSH server is running
  service:
    name: sshd
    enabled: True
    state: started

- name: Copy our fancy SSH banner to /etc/issue
  copy:
    backup: True
    dest: /etc/issue
    mode: 0644
    owner: root
    src: files/banner

- name: Deploy a secure SSH configuration
  notify: Restart SSHD
  template:
    dest: /etc/ssh/sshd_config
    owner: root
    mode: 0600
    src: templates/sshd_config.j2

- name: Enable NOPASSWD sudo elevation
  lineinfile:
    state: present
    validate: 'visudo -cf %s'
    mode: 0440
    owner: root
    path: /etc/sudoers
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'

- name: Install ZeroTier One if it's not already installed
  shell: curl -s https://install.zerotier.com | sudo bash
  when: "'zerotier-one' not in ansible_facts.packages"
  notify:
    - Start ZeroTier
    - Enable ZeroTier

- name: Check if already joined to ZeroTier network
  shell: zerotier-cli status
  register: zerotier_status

- name: Join to ZeroTier network, if not already joined
  shell: zerotier-cli join {{ zerotier_network_id }}
  when: "'{{ zerotier_network_id }}' not in zerotier_status"
  notify:
